### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by zaratan**
This PR introduce tests for all the gem. It covers a huge part of the REST API.

### Added
- Complete test coverage (Unit + Integration tests)
- Adding minimum coverage for tests
- Adding Guard

### Changed
- Fixed many edge-case bugs

### Removed
- Removed the `Gemfile.lock` since it shouldn't be commited in gems

### CODE REVIEW

**Comment by zaratan** [comment]
@patrick-hubert-adsk 
Capture d’écran 2021-06-14 à 18 32 52
Ruby 2.5 isn't supported anymore, can you remove the check ?

**Comment by zaratan** [comment]
Please don't merge it, I need to check with an admin if the release process is working.

**Review by patrick-hubert-adsk — APPROVED** [review]
CR Done.

**Comment by patrick-hubert-adsk** [comment]
Ruby 2.5 : I have no idea of how to remove this. I searched and did not see anything obvious.

**Pull request merged**
